const doctorsData = {
    "professionals": [
        {
            name: "Dr. Smiles Dental Hospitals",
            specialist: "dentist",
            recommended_by: "AD",
            review_count: 2320,
            years_of_experience: "8 - 29",
            location: "Vidyanagar",
            consultation_fee: 300,
            patient_stories: "99%",
            availability: "Book Clinic Visit",
            clinics: null,
            booking_options: null,
            image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SW5kaWFuJTIwZG9jdG9yfGVufDB8fDB8fHww",
          },
          {
            name: "Dr. G.Chandra Sekhar",
            specialist: "dentist",
            recommended_by: "98%",
            review_count: 195,
            years_of_experience: 35,
            location: "Himayat Nagar, Hyderabad",
            clinics: ["Dr. G Chandra Sekhar's Dental Hospital", "Another Clinic"],
            consultation_fee: 500,
            patient_stories: "98%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Hospital"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. K Kiran Kumar",
            specialist: "dentist",
            recommended_by: "99%",
            review_count: 829,
            years_of_experience: 29,
            location: "Vidyanagar, Hyderabad",
            clinics: ["Dr. Smiles Dental Hospitals", "Clinic 2", "Clinic 3"],
            consultation_fee: 300,
            patient_stories: "99%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Hospital"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Usha Kiran",
            specialist: "dentist",
            recommended_by: "99%",
            review_count: 432,
            years_of_experience: 27,
            location: "Vidyanagar, Hyderabad",
            clinics: ["Dr. Smiles Dental Hospitals", "Another Clinic"],
            consultation_fee: 300,
            patient_stories: "99%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Hospital"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Aditya Sandeep Kodati",
            specialist: "dentist",
            recommended_by: "98%",
            review_count: 144,
            years_of_experience: 18,
            location: "Domalguda, Hyderabad",
            clinics: ["Anita Krishna Dental Clinic"],
            consultation_fee: 400,
            patient_stories: "98%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Clinic"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Naresh Kumar V",
            specialist: "dentist",
            recommended_by: "99%",
            review_count: 432,
            years_of_experience: 20,
            location: "Nallakunta, Hyderabad",
            clinics: ["Viva Smilez Dental Hospital"],
            consultation_fee: 300,
            patient_stories: "99%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Hospital"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Arvind Nahata",
            specialist: "dentist",
            recommended_by: "99%",
            review_count: 178,
            years_of_experience: 13,
            location: "Himayat Nagar, Hyderabad",
            clinics: ["Diamond Multispeciality Dental Clinic"],
            consultation_fee: 660,
            patient_stories: "99%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Clinic"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Geetha Rani Kodati",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 1,
            years_of_experience: 18,
            location: "Domalguda, Hyderabad",
            clinics: ["Anita Krishna Dental Clinic"],
            consultation_fee: 400,
            patient_stories: "100%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Clinic"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Namratha CH",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 2,
            years_of_experience: 13,
            location: "Narayanguda, Hyderabad",
            clinics: ["Dental Care Centre"],
            consultation_fee: 500,
            patient_stories: "100%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Clinic"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Ahmed Syed Mubashir",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 2,
            years_of_experience: 10,
            location: "Lakdikapul, Hyderabad",
            clinics: ["Ahmed Dental Care"],
            consultation_fee: 300,
            patient_stories: "100%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Clinic"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. C V Sarath Krishna",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 2,
            years_of_experience: 10,
            location: "Himayat Nagar, Hyderabad",
            clinics: ["Smile Kreations"],
            consultation_fee: 500,
            patient_stories: "100%",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Clinic"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Yashvanth Bethapudi",
            specialist: "dentist",
            recommended_by: "99%",
            review_count: 994,
            years_of_experience: 15,
            location: "Ramkoti, Hyderabad",
            clinics: ["Dr Smiles Dental Clinic Ramkote", "Clinic 2", "Clinic 3", "Clinic 4"],
            consultation_fee: 300,
            patient_stories: "99%",
            availability: "Available Tomorrow",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Clinic"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. K Rohini",
            specialist: "dentist",
            recommended_by: null,
            review_count: null,
            years_of_experience: 12,
            location: "Nallakunta, Hyderabad",
            clinics: ["Partha Dental Skin Hair"],
            consultation_fee: 500,
            patient_stories: null,
            availability: "Available Today",
            booking_options: ["Book Clinic Visit", "No Booking Fee", "Contact Hospital"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Taufiq Munshi",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 3,
            years_of_experience: 28,
            location: "Himayat Nagar, Hyderabad",
            clinics: ["Tooth Care"],
            consultation_fee: 500,
            patient_stories: "100%",
            availability: "Contact Clinic",
            booking_options: ["Book Video Consult"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. V.Bhadra Rao",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 18,
            years_of_experience: 27,
            location: "Ramkoti, Hyderabad",
            clinics: ["Dr Smiles Dental Clinic Ramkote"],
            consultation_fee: 300,
            patient_stories: "100%",
            availability: "ON - CALL",
            booking_options: ["Contact Clinic", "View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Syed Ali Hasnain",
            specialist: "dentist",
            recommended_by: "97%",
            review_count: 37,
            years_of_experience: 8,
            location: "Ramkoti, Hyderabad",
            clinics: ["Dr Smiles Dental Clinic Ramkote", "Another Clinic"],
            consultation_fee: 300,
            patient_stories: "97%",
            availability: "Contact Clinic",
            booking_options: ["View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. G Hemamalini",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 1,
            years_of_experience: 7,
            location: "Himayat Nagar, Hyderabad",
            clinics: ["Smile Kreations"],
            consultation_fee: 500,
            patient_stories: "100%",
            availability: "Contact Clinic",
            booking_options: ["View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Naveen Kumar Reddy K",
            specialist: "dentist",
            recommended_by: null,
            review_count: null,
            years_of_experience: 14,
            location: "Himayat Nagar, Hyderabad",
            clinics: ["Smile Kreations"],
            consultation_fee: 500,
            patient_stories: null,
            availability: "Contact Clinic",
            booking_options: ["View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Riya Goyal",
            specialist: "dentist",
            recommended_by: null,
            review_count: null,
            years_of_experience: 9,
            location: "Ramkoti, Hyderabad",
            clinics: ["Dr Smiles Dental Clinic Ramkote"],
            consultation_fee: 300,
            patient_stories: null,
            availability: "Contact Clinic",
            booking_options: ["View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. D Shirisha",
            specialist: "dentist",
            recommended_by: "100%",
            review_count: 8,
            years_of_experience: 8,
            location: "Vidyanagar, Hyderabad",
            clinics: ["Dr. Smiles Dental Hospitals"],
            consultation_fee: 300,
            patient_stories: "100%",
            availability: "Contact Hospital",
            booking_options: ["View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Alekhya A",
            specialist: "dentist",
            recommended_by: null,
            review_count: null,
            years_of_experience: 11,
            location: "Nallakunta, Hyderabad",
            clinics: ["Apollo Dental"],
            consultation_fee: 500,
            patient_stories: null,
            availability: "Contact Clinic",
            booking_options: ["View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Sivavenkata Malati Nalli",
            specialist: "dentist",
            recommended_by: "98%",
            review_count: 46,
            years_of_experience: 18,
            location: "Ramkoti, Hyderabad",
            clinics: ["Dr Smiles Dental Clinic Ramkote", "Clinic 2", "Clinic 3", "Clinic 4", "Clinic 5", "Clinic 6", "Clinic 7"],
            consultation_fee: 300,
            patient_stories: "98%",
            availability: "ON - CALL",
            booking_options: ["Contact Clinic", "View Profile"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Birla Fertility & IVF",
            specialist: "gynecologist",
            recommended_by: null,
            review_count: null,
            years_of_experience: "12 - 17 years",
            location: "Banjara Hills, Hyderabad",
            clinics: null,
            consultation_fee: "0 (Free Consultation)",
            patient_stories: "11",
            availability: "Available",
            booking_options: ["Book Clinic Visit"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Sridevi Gutta",
            specialist: "gynecologist",
            recommended_by: null,
            review_count: null,
            years_of_experience: "24 years",
            location: "Kachiguda, Hyderabad",
            clinics: ["Prathima Hospitals", "Another Clinic"],
            consultation_fee: "600",
            patient_stories: "52",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Roopa Ghanta",
            specialist: "gynecologist",
            recommended_by: null,
            review_count: null,
            years_of_experience: "30 years",
            location: "Banjara Hills, Hyderabad",
            clinics: ["Little Stars and She Hospital", "Another Clinic"],
            consultation_fee: "600",
            patient_stories: "111",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
          {
            name: "Dr. Narla Ashwani",
            specialist: "gynecologist",
            recommended_by: null,
            review_count: null,
            years_of_experience: "9 years",
            location: "Nallakunta, Hyderabad",
            clinics: ["Seasons Hospital"],
            consultation_fee: "600",
            patient_stories: "1",
            availability: "Available Today",
            booking_options: ["Book Clinic Visit"],
            image: "https://images.pexels.com/photos/8376181/pexels-photo-8376181.jpeg?auto=compress&cs=tinysrgb&w=600",
          },
      {
        "name": "Dr. V Hemalatha Reddy",
        "specialist": "gynecologist",
        "recommended_by": null,
        "review_count": null,
        "years_of_experience": "14 years",
        "location": "Basheerbagh, Hyderabad",
        "clinics": ["Hope Children's Hospital"],
        "consultation_fee": "800",
        "patient_stories": null,
        "availability": "Available Today",
        "booking_options": ["Book Clinic Visit"]
      },
      {
        "name": "Dr. Manav Chintawar",
        "specialist": "gynecologist",
        "recommended_by": null,
        "review_count": null,
        "years_of_experience": "9 years",
        "location": "Ramanthapur, Hyderabad",
        "clinics": ["Manasa Hospital"],
        "consultation_fee": "300",
        "patient_stories": "3",
        "availability": "Available Today",
        "booking_options": ["Book Clinic Visit"]
      },
      {
        "name": "Dr. Amishrita Chintawar",
        "specialist": "gynecologist",
        "recommended_by": null,
        "review_count": null,
        "years_of_experience": "12 years",
        "location": "Ramanthapur, Hyderabad",
        "clinics": ["Manasa Hospital"],
        "consultation_fee": "400",
        "patient_stories": "16",
        "availability": "Available Tomorrow",
        "booking_options": ["Book Clinic Visit"]
      },
      {
        "name": "Dr. Pushpalata Damaraju",
        "specialist": "gynecologist",
        "recommended_by": null,
        "review_count": null,
        "years_of_experience": "57 years",
        "location": "Himayat Nagar, Hyderabad",
        "clinics": ["Lakshmi Hospital & Research Centre"],
        "consultation_fee": "500",
        "patient_stories": "133",
        "availability": null,
        "booking_options": ["Contact Hospital"]
      },
      {
        "name": "Dr. Sagi Swathi",
        "specialist": "gynecologist",
        "recommended_by": null,
        "review_count": null,
        "years_of_experience": "16 years",
        "location": "Himayat Nagar, Hyderabad",
        "clinics": ["Women's Health and Fertility Clinic"],
        "consultation_fee": "500",
        "patient_stories": "5",
        "availability": "Available on Fri, 21 Mar",
        "booking_options": ["Book Clinic Visit"]
      },
      {
        "name": "Dr. M Beulah",
        "specialist": "gynecologist",
        "recommended_by": null,
        "review_count": null,
        "years_of_experience": "12 years",
        "location": "Banjara Hills, Hyderabad",
        "clinics": ["Virinchi Hospitals", "Another Clinic"],
        "consultation_fee": "800",
        "patient_stories": null,
        "availability": null,
        "booking_options": null
      }
    ]
  }

  export {doctorsData}